import { Web3WalletTypes } from '@walletconnect/web3wallet'
import { ethers } from 'ethers'
import {
  ChainMetadatas,
  SupportedCaipNamespace,
  useChainMetadatasCustom,
} from 'features/caip'
import * as React from 'react'
import { fromZodError } from 'zod-validation-error'

import {
  AddEthereumChainRequestParams,
  BlockchainRequestHandlersEip155,
  Eip155RpcMethod,
} from '../@types'

// HACK: Prevent invalid requests from being generated by legacy frontends.
const adjustTransactionData = async ({
  transaction,
}: {
  readonly transaction: Parameters<ethers.Wallet['sendTransaction']>[0]
}) => {
  if (transaction && typeof transaction === 'object') {
    // @ts-expect-error "gas" is no longer supported
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { gas, ...extras } = transaction
    return { ...extras }
  }
  return transaction
}

const addEthereumChainRequestParamsToChainMetadatas = (
  params: AddEthereumChainRequestParams
): ChainMetadatas =>
  params.flatMap(
    ({ rpcUrls /* nonempty */, chainId, chainName: name }): ChainMetadatas => [
      {
        reference: String(parseInt(chainId, 16)),
        namespace: SupportedCaipNamespace.EIP_155,
        name,
        rpcUrls,
      },
    ]
  )

// https://github.com/WalletConnect/web-examples/blob/d7c56a3beaaf75adb0aa481b2010454339361871/wallets/react-wallet-eip155/src/utils/HelperUtil.ts#L23C1-L29C2
const convertHexToUtf8 = (value: string) =>
  ethers.utils.isHexString(value) ? ethers.utils.toUtf8String(value) : value

// https://github.com/WalletConnect/web-examples/blob/d7c56a3beaaf75adb0aa481b2010454339361871/wallets/react-wallet-eip155/src/utils/HelperUtil.ts#L36
const getSignParamsMessage = (params: string[]) => {
  const message = params.filter((p) => !ethers.utils.isAddress(p))[0]
  return convertHexToUtf8(message)
}

const shouldSignMessage = ({
  wallet,
  params,
}: {
  readonly wallet: ethers.Wallet
  readonly params: Web3WalletTypes.EventArguments['session_request']['params']['request']['params']
}) => wallet.signMessage(getSignParamsMessage(params))

// https://github.com/WalletConnect/web-examples/blob/d7c56a3beaaf75adb0aa481b2010454339361871/wallets/react-wallet-eip155/src/utils/HelperUtil.ts#L42C1-L55C2
const getSignTypedDataParamsData = (params: string[]) => {
  const data = params.filter((p) => !ethers.utils.isAddress(p))[0]
  return typeof data === 'string' ? JSON.parse(data) : data
}

const shouldSignTypedData = ({
  params,
  wallet,
}: {
  readonly params: Web3WalletTypes.EventArguments['session_request']['params']['request']['params']
  readonly wallet: ethers.Wallet
}) => {
  const { domain, types, message: data } = getSignTypedDataParamsData(params)
  // https://github.com/ethers-io/ethers.js/issues/687#issuecomment-714069471
  delete types.EIP712Domain
  return wallet._signTypedData(domain, types, data)
}

export function useBlockchainRequestHandlersEip155(): BlockchainRequestHandlersEip155 {
  const { addCustomNetworks } = useChainMetadatasCustom()
  return React.useMemo<BlockchainRequestHandlersEip155>(
    () => ({
      [Eip155RpcMethod.ADD_ETHEREUM_CHAIN]: async ({ params }) => {
        // Here we explicitly ensure all requested chains are valid before attempting
        // to serialize.
        // TODO: It would be less frustrating for the end user if we were to validate
        //       these parameters up front.
        const result = AddEthereumChainRequestParams.safeParse(params)

        if (!result.success) throw fromZodError(result.error)

        return addCustomNetworks(
          addEthereumChainRequestParamsToChainMetadatas(result.data)
        ) /* Promise<[...allCustomNetworks]> */
      },
      [Eip155RpcMethod.PERSONAL_SIGN]: async ({ context: wallet, params }) =>
        shouldSignMessage({ wallet, params }),
      [Eip155RpcMethod.ETH_SIGN]: async ({ context: wallet, params }) =>
        shouldSignMessage({
          wallet,
          params,
        }),
      [Eip155RpcMethod.ETH_SIGN_TRANSACTION]: async ({
        params,
        context: wallet,
      }) => wallet.signTransaction(params[0]),
      [Eip155RpcMethod.ETH_SIGN_TYPED_DATA]: async ({
        context: wallet,
        params,
      }) => shouldSignTypedData({ wallet, params }),
      [Eip155RpcMethod.ETH_SIGN_TYPED_DATA_V3]: async ({
        context: wallet,
        params,
      }) => shouldSignTypedData({ wallet, params }),
      [Eip155RpcMethod.ETH_SIGN_TYPED_DATA_V4]: async ({
        context: wallet,
        params,
      }) => shouldSignTypedData({ wallet, params }),
      [Eip155RpcMethod.ETH_SEND_RAW_TRANSACTION]: async () => {
        // For some reason, WalletConnect have not provided an implementation of send raw transaction.
        // We'll follow suit here in case there's an important reason why.
        // return wallet.sendTransaction(request.params.request.params[0])
        throw new Error(
          `"${Eip155RpcMethod.ETH_SEND_RAW_TRANSACTION}" is not yet supported.`
        )
      },
      [Eip155RpcMethod.ETH_SEND_TRANSACTION]: async ({
        context: wallet,
        params,
      }) => {
        const transactionToSend = await adjustTransactionData({
          transaction: params[0],
        })

        const { hash } = await wallet.sendTransaction(transactionToSend)

        return hash
      },
    }),
    [addCustomNetworks]
  )
}
