import { Web3WalletTypes } from '@walletconnect/web3wallet'
import axios from 'axios'
import { ChainId } from 'caip'
import { ethers } from 'ethers'
import * as React from 'react'
import { fromZodError } from 'zod-validation-error'

import { useChainMetadatasCustom } from '../../hooks'
import { Blockchain, SupportedBlockchainNamespace } from '../../types'
import {
  AddEthereumChainRequestParams,
  BlockchainRequestHandlersEip155,
  Eip155RpcMethod,
} from '../types'

const logger = Logger.create('Blockchains')

// HACK: Prevent invalid requests from being generated by legacy frontends.
const adjustTransactionData = async ({
  transaction,
}: {
  readonly transaction: Parameters<ethers.Wallet['sendTransaction']>[0]
}) => {
  if (transaction && typeof transaction === 'object') {
    // @ts-expect-error "gas" is no longer supported
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { gas, ...extras } = transaction
    return { ...extras }
  }
  return transaction
}

const addEthereumChainRequestParamsToChainMetadatas = (
  params: AddEthereumChainRequestParams
): Blockchain[] =>
  params.flatMap(
    ({
      rpcUrls /* nonempty */,
      chainId,
      chainName: name,
      nativeCurrency: { name: nativeCurrencyName, decimals, symbol },
      icon: maybeIcon,
      blockExplorerUrls,
    }): Blockchain[] => [
      {
        reference: String(parseInt(chainId, 16)),
        namespace: SupportedBlockchainNamespace.EIP_155,
        name,
        rpcUrls,
        nativeCurrencyName,
        decimals,
        symbol,
        blockExplorers: blockExplorerUrls.map((url: string) => ({
          url,
        })),
        // TODO: allow the user to customize the icon
        icon:
          typeof maybeIcon === 'string' && maybeIcon.length ? maybeIcon : null,
        // TODO: don't know if mainnet or testnet
        isMainnet: null,
      },
    ]
  )

// https://github.com/WalletConnect/web-examples/blob/d7c56a3beaaf75adb0aa481b2010454339361871/wallets/react-wallet-eip155/src/utils/HelperUtil.ts#L23C1-L29C2
const convertHexToUtf8 = (value: string) =>
  ethers.utils.isHexString(value) ? ethers.utils.toUtf8String(value) : value

// https://github.com/WalletConnect/web-examples/blob/d7c56a3beaaf75adb0aa481b2010454339361871/wallets/react-wallet-eip155/src/utils/HelperUtil.ts#L36
const getSignParamsMessage = (params: string[]) => {
  const message = params.filter((p) => !ethers.utils.isAddress(p))[0]
  return convertHexToUtf8(message)
}

const shouldSignMessage = ({
  wallet,
  params,
}: {
  readonly wallet: ethers.Wallet
  readonly params: Web3WalletTypes.EventArguments['session_request']['params']['request']['params']
}) => wallet.signMessage(getSignParamsMessage(params))

// https://github.com/WalletConnect/web-examples/blob/d7c56a3beaaf75adb0aa481b2010454339361871/wallets/react-wallet-eip155/src/utils/HelperUtil.ts#L42C1-L55C2
const getSignTypedDataParamsData = (params: string[]) => {
  const data = params.filter((p) => !ethers.utils.isAddress(p))[0]
  return typeof data === 'string' ? JSON.parse(data) : data
}

const shouldSignTypedData = ({
  params,
  wallet,
}: {
  readonly params: Web3WalletTypes.EventArguments['session_request']['params']['request']['params']
  readonly wallet: ethers.Wallet
}) => {
  const { domain, types, message: data } = getSignTypedDataParamsData(params)
  // https://github.com/ethers-io/ethers.js/issues/687#issuecomment-714069471
  delete types.EIP712Domain
  return wallet._signTypedData(domain, types, data)
}

export function useBlockchainRequestHandlersEip155(): BlockchainRequestHandlersEip155 {
  const { addCustomNetworks } = useChainMetadatasCustom()
  return React.useMemo<BlockchainRequestHandlersEip155>(
    () => ({
      [Eip155RpcMethod.ADD_ETHEREUM_CHAIN]: async ({ params }) => {
        // Here we explicitly ensure all requested chains are valid before attempting
        // to serialize.
        // TODO: It would be less frustrating for the end user if we were to validate
        //       these parameters up front.
        const result = AddEthereumChainRequestParams.safeParse(params)

        if (!result.success) throw fromZodError(result.error)

        return addCustomNetworks(
          addEthereumChainRequestParamsToChainMetadatas(result.data)
        ) /* Promise<[...allCustomNetworks]> */
      },
      [Eip155RpcMethod.PERSONAL_SIGN]: async ({ context: wallet, params }) =>
        shouldSignMessage({ wallet, params }),
      [Eip155RpcMethod.ETH_SIGN]: async ({ context: wallet, params }) =>
        shouldSignMessage({
          wallet,
          params,
        }),
      [Eip155RpcMethod.ETH_SIGN_TRANSACTION]: async ({
        params,
        context: wallet,
      }) => wallet.signTransaction(params[0]),
      [Eip155RpcMethod.ETH_SIGN_TYPED_DATA]: async ({
        context: wallet,
        params,
      }) => shouldSignTypedData({ wallet, params }),
      [Eip155RpcMethod.ETH_SIGN_TYPED_DATA_V3]: async ({
        context: wallet,
        params,
      }) => shouldSignTypedData({ wallet, params }),
      [Eip155RpcMethod.ETH_SIGN_TYPED_DATA_V4]: async ({
        context: wallet,
        params,
      }) => shouldSignTypedData({ wallet, params }),
      [Eip155RpcMethod.ETH_SEND_RAW_TRANSACTION]: async () => {
        // For some reason, WalletConnect have not provided an implementation of send raw transaction.
        // We'll follow suit here in case there's an important reason why.
        // return wallet.sendTransaction(request.params.request.params[0])
        throw new Error(
          `"${Eip155RpcMethod.ETH_SEND_RAW_TRANSACTION}" is not yet supported.`
        )
      },
      [Eip155RpcMethod.ETH_SEND_TRANSACTION]: async ({
        context: wallet,
        params,
        chainId,
      }) => {
        logger.info('Sending transaction for native asset', { chainId })

        const gasData = await getGasFees(chainId)
        logger.debug('Gas data for transaction:', gasData)

        const transactionToSend = await adjustTransactionData({
          transaction: {
            ...params[0],
            ...gasData,
          },
        })

        logger.info('Sending crypto transaction')
        const tx = await wallet.sendTransaction(transactionToSend)

        logger.debug('Waiting for transaction')
        await tx.wait()

        const { hash } = tx
        logger.debug('Transaction hash', { hash })

        return hash
      },
    }),
    [addCustomNetworks]
  )
}

async function getGasFees(chainId?: string | ChainId) {
  const formattedChainId = chainId?.toString()
  logger.debug('Getting gas fees', { chainId: formattedChainId })

  const gasStationURL =
    formattedChainId === 'eip155:137'
      ? 'https://gasstation.polygon.technology/v2'
      : formattedChainId === 'eip155:80002'
        ? 'https://gasstation-testnet.polygon.technology/amoy'
        : null

  if (!gasStationURL) {
    return {}
  }

  try {
    const { data } = await axios({
      method: 'get',
      url: gasStationURL,
    })

    const maxFeePerGas = data?.fast?.maxFee
      ? ethers.utils.parseUnits(Math.ceil(data.fast.maxFee) + '', 'gwei')
      : ethers.BigNumber.from('40000000000')

    const maxPriorityFeePerGas = data?.fast?.maxPriorityFee
      ? ethers.utils.parseUnits(
          Math.ceil(data.fast.maxPriorityFee) + '',
          'gwei'
        )
      : ethers.BigNumber.from('50000000000')

    return {
      maxFeePerGas,
      maxPriorityFeePerGas,
    }
  } catch (error) {
    logger.error(error)
    return {}
  }
}
