export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_BIO_AUTH_STATUS = 'SET_BIO_AUTH_STATUS';
export const SET_PUBLIC_PROFILE_DATA = 'SET_PUBLIC_PROFILE_DATA';
export const SET_NEW_MESSAGES_COUNT = 'SET_NEW_MESSAGES_COUNT';
export const SET_INBOX_ITEMS = 'SET_INBOX_ITEMS';
