version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install packages
          command: yarn install --immutable
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Check TS
          command: tsc --noemit

workflows:
  orb-free-workflow:
    jobs:
      - build
