version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: install global dependencies
          command: yarn global add node-pre-gyp && sudo apt-get update && sudo apt-get install -y python
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install packages
          command: npm_config_build_from_source=true yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Check TS
          command: npx tsc --noemit

workflows:
  orb-free-workflow:
    jobs:
      - build
