import Color from 'color'

import {
  BACKGROUND_GREY_COLOR,
  BLACK_COLOR_OPACITY,
  DECLINE_COLOR,
  DEFAULT_ICON_COLOR,
  GREY_120,
  LIGHT_GREY_600,
  LIGHTGREY_COLOR,
  ORANGE_COLOR,
  PRIMARY_COLOR,
  PRIMARY_COLOR_50,
  PRIMARY_COLOR_100,
  SEPARATOR,
  SEPARATOR_EXTRA_LIGHT,
  SHADOW_LIGHT_GREY,
  SNOW_COLOR,
  SUCCESS_COLOR,
  TEXT_COLOR,
  TEXT_GREY_100,
  TEXT_GREY_500,
  TEXT_LIGHT_GREY,
  VERIDA_COLOR,
  VERY_LIGHTGREY_COLOR,
  WARNING_LIGHT_COLOR,
  WHITE_COLOR,
} from 'constants/color'

export const defaultTheme = {
  color: {
    primary: PRIMARY_COLOR,
    onPrimary: WHITE_COLOR,
    background: WHITE_COLOR,
    backgroundGrey: BACKGROUND_GREY_COLOR,
    onBackground: TEXT_COLOR,
    surface: WHITE_COLOR,
    onSurface: TEXT_COLOR,
    onDarkBackground: WHITE_COLOR,

    error: DECLINE_COLOR,
    onError: WHITE_COLOR,
    success: SUCCESS_COLOR,
    onSuccess: WHITE_COLOR,
    warning: WARNING_LIGHT_COLOR,
    overlay: 'rgba(0, 0, 0, 0.6)',
    overlayLight: 'rgba(0, 0, 0, 0.1)',
    shadow: LIGHTGREY_COLOR,
    separator: SEPARATOR,
    separatorExtraLight: SEPARATOR_EXTRA_LIGHT,
    icon: TEXT_COLOR,
    iconDefault: DEFAULT_ICON_COLOR,
    snow: SNOW_COLOR,

    veridaGreen: VERIDA_COLOR,
    orange: ORANGE_COLOR,

    primary50: PRIMARY_COLOR_50,
    primary100: PRIMARY_COLOR_100,

    transparent: 'transparent',
    black800: BLACK_COLOR_OPACITY(0.8),
    black600: BLACK_COLOR_OPACITY(0.6),
    lightGrey: LIGHTGREY_COLOR,
    veryLightGrey: VERY_LIGHTGREY_COLOR,
    textGrey100: TEXT_GREY_100,
    textGrey500: TEXT_GREY_500,
    textGrey600: LIGHT_GREY_600,
    textLightGrey: TEXT_LIGHT_GREY,
    textLightGrey50: Color(TEXT_COLOR).alpha(0.5).toString(),
    grey120: GREY_120,

    shadowLightGrey: SHADOW_LIGHT_GREY,
    placeholderTextColor: BLACK_COLOR_OPACITY(0.3),

    switchFalseState: '#767577',
    switchIOSBg: '#131313',

    grey100: '#EDF0F3',
    grey200: '#DDE3E9',
    grey300: '#CED3DA',
    grey400: '#92979E',
    grey500: '#686D72',
    grey600: '#383A3C',
    grey700: '#26282A',
    grey800: '#18191A',
    grey900: '#0F1011',
  },
  spacing: {
    xs: 4,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 40,
    xxxl: 48,
    xxxxl: 64,
  },
  fontSize: {
    xs: 10,
    s: 12,
    m: 14,
    l: 16,
    sl: 17,
    xl: 18,
    xxl: 22,
    xxxl: 24,
    xxxxl: 36,
  },
  roundness: {
    xs: 4,
    s: 8,
    m: 10,
    l: 12,
    xl: 20,
    xxl: 24,
  },
  iconSize: {
    s: 16,
    m: 24,
  },
}
