import {
  ALERT_INFO_COLOR,
  ALERT_WARNING_COLOR,
  BACKGROUND_GREY_COLOR,
  BLACK_COLOR,
  BLACK_COLOR_OPACITY,
  DECLINE_COLOR,
  LIGHTGREY_COLOR,
  PRIMARY_COLOR,
  SEPARATOR,
  SUCCESS_COLOR,
  TEXT_COLOR,
  TEXT_GREY_100,
  TEXT_GREY_500,
  VERIDA_COLOR,
  VERY_LIGHTGREY_COLOR,
  WHITE_COLOR,
} from 'constants/color'

export const defaultTheme = {
  color: {
    primary: PRIMARY_COLOR,
    primary100: TEXT_COLOR,
    onPrimary: BLACK_COLOR,
    background: WHITE_COLOR,
    backgroundGray: BACKGROUND_GREY_COLOR,
    onBackground: BLACK_COLOR,
    surface: WHITE_COLOR,
    onSurface: BLACK_COLOR,
    onDarkBackground: WHITE_COLOR,

    error: DECLINE_COLOR,
    info: ALERT_INFO_COLOR,
    warning: ALERT_WARNING_COLOR,
    onError: WHITE_COLOR,
    success: SUCCESS_COLOR,
    onSuccess: WHITE_COLOR,
    overlay: 'rgba(0, 0, 0, 0.6)',
    separator: SEPARATOR,

    veridaGreen: VERIDA_COLOR,

    transparent: 'transparent',
    black800: BLACK_COLOR_OPACITY(0.8),
    lightGrey: LIGHTGREY_COLOR,
    veryLightGrey: VERY_LIGHTGREY_COLOR,
    textGrey100: TEXT_GREY_100,
    textGrey500: TEXT_GREY_500,

    gray100: '#EDF0F3',
    gray200: '#DDE3E9',
    gray300: '#CED3DA',
    gray400: '#92979E',
    gray500: '#686D72',
    gray600: '#383A3C',
    gray700: '#26282A',
    gray800: '#18191A',
    gray900: '#0F1011',
  },
  spacing: {
    xs: 4,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
    xl: 36,
    xxl: 40,
    xxxl: 48,
    xxxxl: 64,
  },
  fontSize: {
    s: 12,
    m: 14,
    l: 16,
    xl: 18,
    xxl: 24,
    xxxl: 36,
  },
  borderRadius: {
    xs: 4,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
  },
}
